version: "3.3"

services:
  gazebo: 
    # build:
    #   context: ./gazebo
    #   dockerfile: Dockerfile
    image: tianyaoh501679/tianyaoh-cp22:tortoisebot-ros2-gazebo
    hostname: tortoisebot-ros2-gazebo
    # command: tail -f /dev/null
    command: bash -c "source /root/ros2_ws/install/setup.bash && ros2 launch tortoisebot_bringup bringup.launch.py use_sim_time:=True"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://tortoisebot-ros2-gazebo:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/ros2_ws/src/tortoisebot/:/root/ros2_ws/src/tortoisebot
    networks:
      - ros2_net

  mapping:
    # build:
    #   context: ./slam
    #   dockerfile: Dockerfile
    image: tianyaoh501679/tianyaoh-cp22:tortoisebot-ros2-slam
    hostname: tortoisebot-ros2-slam
    restart: always
    depends_on:
      - gazebo
    command: bash -c "source /root/ros2_ws/install/setup.bash && ros2 launch tortoisebot_slam cartographer.launch.py use_sim_time:=True"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://tortoisebot-ros2-gazebo:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/ros2_ws/src/tortoisebot/:/root/ros2_ws/src/tortoisebot
    networks:
      - ros2_net

networks:
  ros2_net: