version: "3.3"

services:
  gazebo: 
    build:
      context: ./gazebo
      dockerfile: Dockerfile
    image: ros2_gazebo:latest
    hostname: tortoisebot-ros2-gazebo
    # command: tail -f /dev/null
    command: bash -c "source /root/ros2_ws/install/setup.bash && ros2 launch tortoisebot_bringup bringup.launch.py use_sim_time:=True"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://tortoise-gazebo-sim:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/ros2_ws/src/tortoisebot/:/root/ros2_ws/src/tortoisebot
    networks:
      - ros2_net

networks:
  ros2_net: