services:
  bringup: 
    build:
      context: ./bringup
      dockerfile: Dockerfile
    image: ros2_bringup:latest
    hostname: tortoisebot-ros2-bringup
    network_mode: host
    cap_add:
      - SYS_RAWIO
    security_opt:
      - "no-new-privileges:true"
    command: bash -c "source install/setup.bash && ros2 launch tortoisebot_bringup bringup.launch.py use_sim_time:=False"
    # command: tail -f /dev/null
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/video0:/dev/video0"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=master
    volumes:
      - /home/tortoisebot/.Xauthority:/root/.Xauthority 
      - ~/ros2_ws/:/root/ros2_ws/

  slam:
    build:
      context: ./slam 
      dockerfile: Dockerfile
    image: ros2_slam:latest
    hostname: tortoisebot-ros2-slam
    network_mode: host
    restart: always
    depends_on:
      - bringup
    command: bash -c "source /root/ros2_ws/install/setup.bash && ros2 launch tortoisebot_slam cartographer.launch.py use_sim_time:=False"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=master
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/ros2_ws/:/root/ros2_ws/
