# Use a custom ROS 2 image as the base
FROM ros2_bringup:latest

# Make sure the package lists are up-to-date
RUN echo "source /opt/ros/galactic/setup.bash" >> ~/.bashrc

# Set the working directory
WORKDIR /root/ros2_ws

